#!/bin/sh
set -o errexit
echo -n 'version: '
read VERSION
echo -n 'min core version: '
read MINIMUM_CORE_VERSION
echo -n 'max core version: '
read COMPATIBLE_CORE_VERSION
cat >module.json <<EOF
{
    "name" : "lang-se",
    "title" : "Terminus [Core]",
    "version" : "$VERSION",
    "minimumCoreVersion" : "$MINIMUM_CORE_VERSION",
    "compatibleCoreVersion" : "$COMPATIBLE_CORE_VERSION",
    "compatibility": {
        "minimum": "$MINIMUM_CORE_VERSION",
        "verified": "$COMPATIBLE_CORE_VERSION"
    },
    "author" : "Fottow",
    "description" : "Terminus language support for Foundry VTT",
    "coreTranslation": true,
    "languages" : [
      {
         "lang" : "se",
         "name" : "Terminus",
         "path" : "te.json"
      }
    ],
    "packs" : [],
    "scripts" : [],
    "styles" : [],
    "url" : "https://github.com/PatrikOAndersson/foundryvtt-lang-terminus",
    "manifest" : "https://raw.githubusercontent.com/PatrikOAndersson/foundryvtt-lang-terminus/main/module.json",
    "download" : "https://github.com/PatrikOAndersson/foundryvtt-lang-terminus/archive/v$VERSION.zip",
    "authors": [
      {
        "name": "Patrik Andersson",
        "url": "https://www.yoghurtspasm.com",
        "discord": "fottow"
      }
    ],
  "media": [
    {
      "type": "icon",
      "url": "https://raw.githubusercontent.com/PatrikOAndersson/foundryvtt-lang-terminus/main/foundry_lang_sv.svg"
    },
    {
      "type": "cover",
      "url": https://raw.githubusercontent.com/PatrikOAndersson/foundryvtt-lang-terminus/main/foundry_lang_sv.svg"
    },
    {
      "type": "setup",
      "caption": "Foundry for Terminus",
      "thumbnail": "/modules/lang-te/foundry_lang_sv.svg"
    }
  ],
  "flags": {
    "media": [
      {
        "type": "cover",
        "url": "https://raw.githubusercontent.com/PatrikOAndersson/foundryvtt-lang-terminus/main/foundry_lang_sv.svg"
      }
    ],
    "manifestPlusVersion": "1.2.0",
    "allowBugReporter": true
  }
}
EOF
git add --all
git commit -m "Released version $VERSION"
git tag --force "v$VERSION"
git push --tags --force
git push